data:
  img_size: 224
  batch_size: 32

training:
  freeze_epochs: 5
  unfreeze_epochs: 5
  freeze_lr: 0.001
  unfreeze_lr: 0.0001

model:
  name: "efficientnet_b0"
  num_classes: 120
  
experiment:
  project_name: "dog-breed-classification"
  name: "efficientnet_b0"
  tags: ["transfer learning"]