data:
  img_size: 224
  batch_size: 32

training:
  freeze_epoch: 5
  unfreeze_epochs: 5
  learning_rate: 0.001

model:
  name: "resnet50"
  num_classes: 120
  
experiment:
  project_name: "dog-breed-classification"
  name: "resnet50"
  tags: "transfer learning"